//! Bounds and seeds for oracle core.

pub use nuvex_common::{
    JOB_CONFIG_SEED, MAX_CALLBACK_DATA_LEN, MAX_INPUT_LEN, MAX_TIMEOUT_SLOTS, MIN_TIMEOUT_SLOTS,
    NODE_SEED, PROTOCOL_SEED, REGISTRY_SEED, REQUEST_ID_LEN, REQUEST_SEED,
};
